font_family      Monaco
font_size        18.0
symbol_map U+E0A0-U+E0A3,U+E0B0-U+E0B3,U+E0C0-U+E0C8,U+23FB-U+23FE,U+2665,U+26A1,U+2B58,U+E000-U+F8FF,U+F0001-U+F1AF0 MesloLGMDZ Nerd Font Mono

# Clipboard
map cmd+c         copy_to_clipboard
map cmd+v         paste_from_clipboard

# Search
map cmd+f         show_scrollback
